[tool.poetry]
name = "appmap"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^5.3.1"
orjson = "^3.4.4"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pytest-randomly = "^3.5.0"
pylint = "^2.6.0"
flake8 = "^3.8.4"
pyfakefs = "^4.3.2"
coverage = "^5.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
